opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicity_unwrapped_optionals
  - multiline_parameters
  - overidden_super_call
  - sorted_imports
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call

disabled_rules:
  - statement_position
  - identifier_name
  - cyclomatic_complexity
  - line_length
  - private_over_fileprivate
  - conditional_returns_on_newline
  - attributes

file_length:
  warning: 1500
  error: 2000

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 500
  error: 750

function_body_length:
  warning: 100
  error: 200

excluded:
  - QVRWeekView/Classes/Support
